// <auto-generated />
using System;
using ExpenseAnalyzer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseAnalyzer.Migrations
{
    [DbContext(typeof(ExpenseAnalyzerContext))]
    [Migration("20220517184840_AddVendor")]
    partial class AddVendor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExpenseAnalyzer.Entities.CategoryMaster", b =>
                {
                    b.Property<short>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("UId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Uid"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Uid");

                    b.ToTable("CategoryMaster", (string)null);
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.Transaction", b =>
                {
                    b.Property<long>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Uid"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime");

                    b.Property<long>("TransactionCategoryUid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("TypeUid")
                        .HasColumnType("tinyint")
                        .HasColumnName("TypeUId");

                    b.Property<long?>("VendorUid")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("VendorUId");

                    b.HasKey("Uid");

                    b.HasIndex("TypeUid");

                    b.HasIndex("VendorUid");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.TypeMaster", b =>
                {
                    b.Property<byte>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("UId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Uid"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Uid");

                    b.ToTable("TypeMaster", (string)null);
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.Vendor", b =>
                {
                    b.Property<long>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Uid"), 1L, 1);

                    b.Property<short?>("CategoryMasterUid")
                        .IsRequired()
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Uid");

                    b.HasIndex("CategoryMasterUid");

                    b.ToTable("Vendor", (string)null);
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.Transaction", b =>
                {
                    b.HasOne("ExpenseAnalyzer.Entities.TypeMaster", "TypeMaster")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseAnalyzer.Entities.Vendor", "Vendor")
                        .WithMany("Transactions")
                        .HasForeignKey("VendorUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeMaster");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.Vendor", b =>
                {
                    b.HasOne("ExpenseAnalyzer.Entities.CategoryMaster", "CategoryMaster")
                        .WithMany("Vendors")
                        .HasForeignKey("CategoryMasterUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryMaster");
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.CategoryMaster", b =>
                {
                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.TypeMaster", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.Vendor", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
