// <auto-generated />
using System;
using ExpenseAnalyzer.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseAnalyzer.Migrations
{
    [DbContext(typeof(ExpenseAnalyzerContext))]
    [Migration("20220516153621_CreateExpenseAnalyzerDB")]
    partial class CreateExpenseAnalyzerDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExpenseAnalyzer.Entities.CategoryMaster", b =>
                {
                    b.Property<short>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("UId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Uid"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Uid");

                    b.ToTable("CategoryMaster", (string)null);
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.Transaction", b =>
                {
                    b.Property<long>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Uid"), 1L, 1);

                    b.Property<short?>("CategoryUid")
                        .HasColumnType("smallint")
                        .HasColumnName("CategoryUId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("TypeUid")
                        .HasColumnType("tinyint")
                        .HasColumnName("TypeUId");

                    b.HasKey("Uid");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("ExpenseAnalyzer.Entities.TypeMaster", b =>
                {
                    b.Property<byte>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("UId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Uid"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Uid");

                    b.ToTable("TypeMaster", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
